//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjCooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t參加者
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t參加者()
        {
            this.t評價 = new HashSet<t評價>();
        }
    
        public int f參加者Id { get; set; }
        public int f會員Id { get; set; }
        public int f聚會Id { get; set; }
        public Nullable<bool> f審核狀態 { get; set; }
        public bool f報名 { get; set; }
        public System.DateTime f參加者建立日期 { get; set; }
    
        public virtual t會員 t會員 { get; set; }
        public virtual t聚會 t聚會 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t評價> t評價 { get; set; }
    }
}
