//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjCooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t留言
    {
        public int f留言Id { get; set; }
        public int f留言人Id { get; set; }
        public int f留言的聚會Id { get; set; }
        public string f留言文字 { get; set; }
        public Nullable<System.DateTime> f留言建立日期 { get; set; }
    
        public virtual t會員 t會員 { get; set; }
        public virtual t聚會 t聚會 { get; set; }
    }
}
