//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjCooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t聚會
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t聚會()
        {
            this.t參加者 = new HashSet<t參加者>();
            this.t評價 = new HashSet<t評價>();
            this.t建議食材 = new HashSet<t建議食材>();
        }
    
        public int f聚會Id { get; set; }
        public int f主辦人 { get; set; }
        public string f聚會名稱 { get; set; }
        public string f聚會內容 { get; set; }
        public string f聚會照片 { get; set; }
        public System.DateTime f聚會日期 { get; set; }
        public System.DateTime f聚會開始時間 { get; set; }
        public Nullable<System.DateTime> f聚會結束時間 { get; set; }
        public Nullable<int> f名額 { get; set; }
        public string f聚會軟體 { get; set; }
        public string f聚會軟體URL { get; set; }
        public string f聚會關鍵字 { get; set; }
        public string f聚會通訊軟體 { get; set; }
        public string f聚會通訊軟體帳號 { get; set; }
        public Nullable<int> f聚會狀態 { get; set; }
        public Nullable<bool> f聚會垃圾桶 { get; set; }
        public System.DateTime f聚會建立日期 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t參加者> t參加者 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t評價> t評價 { get; set; }
        public virtual t會員 t會員 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t建議食材> t建議食材 { get; set; }
    }
}
